// Generated by CoffeeScript 1.3.3

/*

# 在庫管理
#https://sellercentral.amazon.co.jp/myi/search/ProductSummary
*/


(function() {
  var casper, conf, getTrs, trs;

  casper = require("casper").create();

  conf = require("./config");

  casper.start("https://sellercentral.amazon.co.jp/myi/search/ProductSummary", function() {
    this.viewport(1024, 768);
    return this.capture("amatest1.png");
  });

  casper.then(function() {
    return this.fill('form[name=signin]', {
      email: conf.amazon.email,
      password: conf.amazon.password
    }, true);
  });

  trs = [];

  getTrs = function() {
    trs = document.querySelectorAll('tr[id|=sku]');
    return Array.prototype.map.call(trs, function(el) {
      return el.getAttribute('id');
    });
  };

  casper.then(function() {
    var tr, _i, _len, _results;
    this.capture("amatest2.png");
    trs = this.evaluate(getTrs);
    _results = [];
    for (_i = 0, _len = trs.length; _i < _len; _i++) {
      tr = trs[_i];
      _results.push(this.echo(tr));
    }
    return _results;
  });

  casper.run(function() {
    return this.exit();
  });

}).call(this);
