// Generated by CoffeeScript 1.3.1
(function() {
  var AmazonManager, amaMan, conf, db, marketplaceID, options;

  AmazonManager = require('./lib/amazon').AmazonManager;

  db = require('./lib/db');

  conf = require('./config');

  marketplaceID = null;

  options = {
    debug: 1
  };

  if (conf.http.proxy != null) {
    options.proxy = "" + conf.http.proxy + ":" + conf.http.port;
  }

  amaMan = new AmazonManager(options, function(err, ama) {
    var add, signin, signout, update;
    if (err) {
      throw err;
    }
    /*
      totalAmount = am.api.sync am, 'productSummary'
      console.log "totalAmount: #{totalAmount}"
    */

    /*
      items = am.api.sync am, 'productList'
      console.log "items: #{items} items.length: #{items.length}"
      for item, i in items
        console.log "item[#{i}]: #{JSON.stringify item}"
    */

    /*
      result = am.api.sync am, 'remove',
        asin: '4274067149'
      console.log "result:#{result}"
    */

    signin = function(conf, cb) {
      if (conf == null) {
        conf = conf.amazon;
      }
      return ama.api('signin', conf, function(err, mID) {
        marketplaceID = mID;
        console.log("signin complete: " + (new Date));
        console.log("marketplaceID: " + marketplaceID);
        return cb(err, marketplaceID);
      });
      /*
          result = am.api.sync am, 'add',
            asin:'477414813X'   ## 必須
            sellPrice: 3024     ## 必須
            condition: 'Used|LikeNew'
            conditionNote: 'ほぼ新品同様で美品です。'
          console.log "result: #{result}"
      */

    };
    add = function(product, cb) {
      product.amount = 1;
      if (product.condition == null) {
        product.condition = 'Used|Acceptable';
      }
      if (product.conditionNote == null) {
        product.conditionNote = '多少きず等ありますが使用には支障のないレベルです。';
      }
      return ama.api('add', product, function(err, result) {
        console.log("result:" + result);
        return cb(err, result);
      });
      /*
          result = am.api.sync am, 'update',
            asin: '4274067149'
            marketplaceID: marketplaceID
            sellPrice: 3249
            amount: 0
            condition: 'Used|Acceptable'
            conditionNote: '多少きず等ありますが使用には支障のないレベルです。'
          console.log "result:#{result}"
      */

    };
    update = function(product, cb) {
      if (product.marketplaceID == null) {
        product.marketplaceID = marketplaceID;
      }
      return ama.api('update', product, function(err, result) {
        console.log("result:" + result);
        return cb(err, result);
      });
    };
    signout = function() {
      return ama.api('signout', function(err) {
        return console.log('signout complete');
      });
    };
    return db.open(conf.db, function(err, client) {
      var Temp, min_gross_profit, min_gross_profit_ratio;
      if (err) {
        throw err;
      }
      Temp = client.collection('temp');
      min_gross_profit = 1000;
      return min_gross_profit_ratio = 0.6;
    });
  });

}).call(this);
