// Generated by CoffeeScript 1.3.1
(function() {
  var JANS, apac, conf;

  apac = require('./lib/apac');

  conf = require('./config');

  JANS = ['9784338218023', '9784904336236'];

  apac.getApaclist(conf.amazon, JANS, function(err, items) {
    var item, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = items.length; _i < _len; _i++) {
      item = items[_i];
      _results.push(console.log(JSON.stringify(item, null, "  ")));
    }
    return _results;
  });

}).call(this);
