// Generated by CoffeeScript 1.3.3
(function() {
  var bo, conf, db, getBOGenreList, getBOStockList;

  conf = require('./config');

  db = require('./lib/db');

  bo = require('./lib/bookoff');

  getBOGenreList = function(cb, retry) {
    var name;
    if (retry == null) {
      retry = 0;
    }
    name = "getBOGenreList";
    setTimeout(function() {
      return bo.getBOGenreList(conf, function(err, result) {
        if (err === null) {
          return cb(null, result);
        }
        console.log("Error: " + err);
        return setTimeout(function() {
          console.log("" + name + ": retry=" + (++retry));
          return getBOGenreList(cb, retry);
        }, 15 * 1000);
      });
    }, 200);
  };

  getBOStockList = function(id, page, cb, retry) {
    var name;
    if (retry == null) {
      retry = 0;
    }
    name = "getBOStockList";
    setTimeout(function() {
      return bo.getBOStockList(conf, id, page, function(err, result) {
        if (err === null) {
          return cb(null, result);
        }
        console.log("Error: " + err);
        return setTimeout(function() {
          console.log("" + name + ": retry=" + (++retry));
          return getBOStockList(id, page, cb, retry);
        }, 15 * 1000);
      });
    }, 200);
  };

  db.open(conf.db, function(err, client) {
    var Commodities, Temp;
    if (err) {
      throw err;
    }
    Commodities = client.collection('commodities');
    Temp = client.collection('temp');
    Commodities.update({
      amount: 1
    }, {
      $set: {
        amount: 0
      }
    }, {
      multi: true
    });
    Temp.update({
      amount: 1
    }, {
      $set: {
        amount: 0
      }
    }, {
      multi: true
    });
    return getBOGenreList(function(err, genres) {
      var depth, len, map, maxpage, total_count;
      if (err) {
        return console.log("Error: " + err);
      }
      console.log("genres:", genres);
      len = genres.length;
      console.log("len: " + len);
      maxpage = (depth = conf.bookoff.depth) > 0 ? depth : 1000 * 1000;
      total_count = 0;
      map = function(i) {
        var genre, genre_total, map2;
        console.log("map " + i + " / " + len);
        if (i === len) {
          console.log("end");
          process.exit();
        }
        if ((genre = genres[i])) {
          genre = genres[i];
          genre_total = 0;
          map2 = function(page, retry) {
            if (retry == null) {
              retry = 0;
            }
            console.log("map2 " + genre.id + ", " + page);
            return getBOStockList(genre.id, page, function(err, stocks) {
              var amount, detail, doc, options, pnew, pold, query, st, update, _i, _len, _ref;
              if (err) {
                console.log("Error: " + err);
              }
              genre_total = (st = stocks != null ? stocks.total : void 0) > 0 ? st : genre_total;
              if (!(st > 0)) {
                if (++retry < 10) {
                  console.log("search no = 0, retry = " + retry);
                  return process.nextTick((function() {
                    return map2(page, retry);
                  }));
                } else {
                  console.log("retry max, next page");
                  stocks.list = [];
                }
              }
              console.log("page*20: " + (page * 20) + ", total: " + genre_total + " page: " + page + ", maxpage: " + maxpage);
              _ref = stocks.list;
              for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
                detail = _ref[i];
                doc = {
                  sku: detail.sku
                };
                doc.amount = amount = detail.amount;
                doc.pold = pold = detail.price.old;
                doc.pnew = pnew = detail.price['new'];
                console.log(i, JSON.stringify(doc));
                query = {
                  sku: doc.sku
                };
                update = {
                  $set: doc
                };
                options = {
                  safe: true,
                  upsert: true
                };
                Commodities.update(query, {
                  $set: {
                    amount: amount,
                    "price.old": pold,
                    "price.new": pnew
                  }
                });
                Temp.update(query, update);
              }
              if (page * 20 < genre_total && page < maxpage) {
                return process.nextTick((function() {
                  return map2(page + 1);
                }));
              } else {
                return process.nextTick((function() {
                  return map(i + 1);
                }));
              }
            });
          };
          return map2(1);
        } else {
          console.log("deleted");
          return process.nextTick((function() {
            return map(i + 1);
          }));
        }
      };
      return map(0);
    });
  });

}).call(this);
