// Generated by CoffeeScript 1.3.3
(function() {
  var conf, db, dbclose;

  conf = require('./config');

  db = require('./lib/db');

  /*
   * TODO: 前回のCommoditiesがあれば、そのJANをハッシュに保存する
  */


  dbclose = function(client) {
    console.log("db close()");
    return client.close();
  };

  db.open(conf.db, function(err, client) {
    var Commodities, cursor, fields, hash, index, len, makeHash, options, query;
    if (err) {
      throw err;
    }
    Commodities = client.collection('commodities');
    query = {
      JAN: {
        $ne: ''
      }
    };
    fields = {
      JAN: 1,
      _id: 0
    };
    options = {
      sort: {
        JAN: 1
      }
    };
    index = 0;
    len = 1000 * 1000;
    Commodities.count(query, function(err, count) {
      if (err) {
        throw err;
      }
      console.log("total_size = " + count);
      return len = count;
    });
    cursor = Commodities.find(query, fields, options);
    cursor.rewind();
    hash = [];
    makeHash = function() {
      return cursor.nextObject(function(err, doc) {
        if (!doc) {
          return dbclose(client);
        }
        hash[doc.JAN] = true;
        return process.nextTick(function() {
          return makeHash();
        });
      });
    };
    return makeHash();
  });

}).call(this);
