// Generated by CoffeeScript 1.3.3
(function() {
  var conf, db;

  conf = require('./config');

  db = require('./lib/db');

  /*
   * TODO: 前回のCommoditiesがあれば、そのJANをハッシュに保存する
  */


  db.open(conf.db, function(err, client) {
    var Commodities, fields, index, options, query;
    if (err) {
      throw err;
    }
    Commodities = client.collection('commodities');
    query = {
      JAN: {
        $ne: ''
      }
    };
    fields = {
      JAN: 1,
      _id: 0
    };
    options = {
      sort: 'JAN'
    };
    index = 0;
    Commodities.count(query, function(err, count) {
      if (err) {
        throw err;
      }
      return console.log("total_size = " + count);
    });
    return Commodities.find(query, fields, options).each(function(err, doc) {
      return console.log(++index, doc);
    });
  });

}).call(this);
