// Generated by CoffeeScript 1.3.1
(function() {
  var Sync, mongodb;

  Sync = require('sync');

  mongodb = require('mongodb');

  Sync(function() {
    var Item, a, client, db, items, server, _i;
    server = new mongodb.Server('localhost', 27017, {});
    db = new mongodb.Db('test', server, {});
    console.log("db: " + (JSON.stringify(db)));
    client = db.open.sync(null);
    Item = client.collection('items');
    items = [];
    for (a = _i = 1; _i <= 10; a = ++_i) {
      items[a - 1] = {
        name: 'a' + a,
        code: a * 3 - 2
      };
    }
    return Item.insert(items, {
      safe: true
    }, function(err, docs) {
      console.log(docs);
      return client.close();
    });
  });

}).call(this);
