// Generated by CoffeeScript 1.3.1
(function() {
  var conf, ftp;

  ftp = require('./lib/ftp').ftp;

  conf = require('./config');

  ftp(conf.seed, conf.ftp, function(err, stream) {
    var os;
    os = process.stdout;
    return stream.pipe(os);
  });

}).call(this);
