// Generated by CoffeeScript 1.3.3
(function() {
  var conf, db;

  conf = require('./config');

  db = require('./lib/db');

  db.open(conf.db, function(err, client) {
    var Commodities, fields, index, options, query;
    if (err) {
      throw err;
    }
    Commodities = client.collection('commodities');
    query = {
      $or: [
        {
          "amazon.old": {
            $gt: 1000
          }
        }, {
          "amazon.old": 0,
          "amazon.new": 0
        }
      ]
    };
    fields = {
      _id: 0,
      JAN: 1,
      "amazon.asin": 1,
      "price.old": 1,
      "price.new": 1,
      "amazon.old": 1,
      "amazon.new": 1
    };
    options = {
      sort: "price.old"
    };
    index = 0;
    return Commodities.find(query, fields, options).each(function(err, doc) {
      if (err) {
        throw err;
      }
      console.log(index++, JSON.stringify(doc));
      if (index === 100) {
        client.close();
        return process.exit();
      }
    });
  });

}).call(this);
