// Generated by CoffeeScript 1.3.1
(function() {
  var bo, conf, db, limit, no_new_rate, no_used_rate, out_collection, skip, total_size;

  conf = require('./config');

  db = require('./lib/db');

  bo = require('./lib/bookoff');

  if (process.argv.length >= 3) {
    skip = Number(process.argv[2]);
    console.log("skip: " + skip);
  } else {
    skip = 0;
  }

  no_used_rate = 0.8;

  no_new_rate = 10.0;

  out_collection = "temp";

  limit = 10000;

  total_size = 20000;

  db.open(conf.db, function(err, client) {
    var Commodities, Manage, Temp, fields, index, map, options, query;
    if (err) {
      throw err;
    }
    Commodities = client.collection('commodities');
    Temp = client.collection('temp');
    Manage = client.collection('manage');
    query = {
      gross_profit: {
        $gte: 1000
      }
    };
    fields = {
      _id: 0
    };
    options = {
      sort: [["gross_profit", -1]]
    };
    if (limit > 0) {
      options.limit = limit;
    }
    index = 0;
    map = function(skip) {
      index = skip;
      console.log("skip: " + skip + "/total_size: " + total_size);
      if (skip === total_size) {
        client.close();
        process.exit();
      }
      if (skip > 0) {
        options.skip = skip;
      }
      return Temp.find(query, fields, options).toArray(function(err, docs) {
        var len, map2;
        if (err) {
          console.log("Error: " + err + " and retry");
          setTimeout((function() {
            return map(skip);
          }), 15 * 1000);
          return;
        }
        len = docs.length;
        map2 = function(i) {
          var doc;
          if (i === len) {
            index--;
            process.nextTick(function() {
              return map(skip + limit);
            });
            return;
          }
          doc = docs[i];
          if (doc.sku != null) {
            return setTimeout(function() {
              return bo.getBOItemDetail(doc.sku, conf, function(err, detail) {
                var amount, func, options2, pnew, pold, query2, update;
                if (err) {
                  console.log("Error: " + err + " and retry");
                  setTimeout((function() {
                    return map2(i);
                  }), 15 * 1000);
                  return;
                }
                if (detail.amount != null) {
                  doc.amount = amount = detail.amount;
                  doc.pold = pold = detail.price.old;
                  doc.pnew = pnew = detail.price['new'];
                  console.log(index++, JSON.stringify(doc));
                  query2 = {
                    sku: doc.sku
                  };
                  update = {
                    $set: doc
                  };
                  options2 = {
                    safe: true,
                    upsert: true
                  };
                  Commodities.update(query2, {
                    $set: {
                      amount: amount,
                      "price.old": pold,
                      "price.new": pnew
                    }
                  });
                  func = function() {
                    return Temp.update(query2, update, options2, function(err, count) {
                      if (err) {
                        console.log("Error: " + err + " and retry");
                        setTimeout((function() {
                          return func();
                        }), 100);
                      }
                    });
                  };
                  func();
                  return map2(i + 1);
                } else {
                  console.log(index++, detail);
                  return map2(i + 1);
                }
              });
            }, 200);
          }
        };
        return map2(0);
      });
    };
    return Temp.count(query, function(err, count) {
      total_size = Math.ceil(count / limit) * limit;
      return map(skip);
    });
  });

}).call(this);
