// Generated by CoffeeScript 1.3.3
(function() {
  var Ftp;

  Ftp = require('ftp');

  exports.ftp = function(filename, conf, callback) {
    var auth, connect, host, pass;
    if (callback == null) {
      callback = function() {};
    }
    host = conf.firewall != null ? conf.firewall : conf.host;
    auth = conf.firewall != null ? "" + conf.user + "@" + conf.host : conf.user;
    pass = conf.pass;
    connect = new Ftp({
      host: host
    });
    connect.connect();
    return connect.on('connect', function() {
      return connect.auth(auth, pass, function(err) {
        if (err) {
          return callback(err);
        }
        return connect.get(filename, function(err, stream) {
          if (err) {
            return callback(err);
          }
          stream.on('success', function() {
            return connect.end();
          }).on('error', function(err) {
            return callback(err);
          });
          return callback(null, stream);
        });
      });
    });
  };

}).call(this);
