// Generated by CoffeeScript 1.3.1
(function() {
  var httpGet, strong, urlJan, urlSplit, urlTop;

  httpGet = require('./httpGet').httpGet;

  /*
  //
  // pricecheckに関する細かな定義
  // 
  //  ・JAN(EAN)により、最大10個まで検索可能
  //  
  //  http://so-bank.jp/choice/?ean=9784876999767+%0D%0A9784839941239+%0D%0A9784401748693+%0D%0A9784120042201+%0D%0A9784860850999+%0D%0A9784776808121+%0D%0A9784046217585+%0D%0A9784336052117+%0D%0A9784490206937+%0D%0A9784829144916+%0D%0A
  */


  urlTop = 'http://so-bank.jp';

  urlJan = '/choice/?ean=';

  urlSplit = '+%0D%0A';

  strong = function(self, result, key) {
    var re;
    re = self.find('strong').text().match(/\d+/);
    return result[key] = re ? Number(re[0]) : 0;
  };

  /*
  // PriceCheck : JAN(最大10件)に対応するAmazon（PriceCheck）情報を取得
  // input      : conf コンフィギュレーション
  // input      : JANS 配列（最大10件）
  // output : callback(err, genre) コールバック関数 genreはジャンル情報リスト(配列)
  */


  exports.getPCInfolist = function(conf, JANS, callback) {
    var JAN, url, _i, _len;
    url = urlTop + urlJan;
    for (_i = 0, _len = JANS.length; _i < _len; _i++) {
      JAN = JANS[_i];
      url = url + JAN + urlSplit;
    }
    console.log("url: " + url);
    return httpGet(url, conf.http, function(err, $) {
      var $searchResult, results;
      if (err) {
        return callback(err);
      }
      results = [];
      $searchResult = $('.searchResult');
      $searchResult.each(function(index) {
        var asin, pcUrl, result, self;
        self = $(this);
        pcUrl = $('.searchResult_img a', self).attr('href');
        asin = pcUrl.replace('/detail/?code=', '');
        result = {
          JAN: JANS[index],
          asin: asin,
          url: urlTop + pcUrl
        };
        $($($(self.children()[1]).children()).children()).each(function(index2) {
          self = $(this);
          switch (index2) {
            case 0:
              return result.title = self.find('a').text();
            case 1:
              return result.author = self.text();
            case 2:
              return strong(self, result, 'new');
            case 3:
              return strong(self, result, 'old');
            case 4:
              return strong(self, result, 'past');
            case 5:
              return strong(self, result, 'diff');
            case 6:
              return strong(self, result, 'rank');
          }
        });
        return results[index] = result;
      });
      return callback(null, results);
    });
  };

}).call(this);
