// Generated by CoffeeScript 1.3.1

/*
##  stream.coffee : pipable stream skelton
##
##  TODO: pause, resume or another unsupported
##        (to be referring the 'event-stream')
*/


(function() {
  var stream;

  stream = function() {
    stream = new Stream;
    stream.writable = true;
    stream.readable = true;
    stream.write = function(buffer) {
      var data;
      data = buffer;
      stream.emit('data', buffer);
      return true;
    };
    stream.end = function() {
      return stream.emit('end');
    };
    return stream;
  };

}).call(this);
