// Generated by CoffeeScript 1.3.3
(function() {
  var os, rs, zlib;

  zlib = require('zlib');

  rs = process.openStdin();

  os = process.stdout;

  rs.pipe(zlib.createGunzip()).pipe(os);

}).call(this);
